--INSERT INTO holidays (holiday,reason,type)VALUES('Jan 1','New-Year','FESTIVAL');
--INSERT INTO holidays (holiday,reason,type)VALUES(' Oct 31 ','Halloween','FESTIVAL');
--INSERT INTO holidays (holiday,reason,type)VALUES(' Nov 24 ','Thanksgiving Day','FESTIVAL');
--INSERT INTO holidays (holiday,reason,type)VALUES(' Dec 25 ','Christmas Eve','FESTIVAL');
--INSERT INTO holidays (holiday,reason,type)VALUES(' Jan 17 ','Sr Martin Luther King Day','FEDERAL');
--INSERT INTO holidays (holiday,reason,type)VALUES(' July 4 ','Independence Day','FEDERAL');
--INSERT INTO holidays (holiday,reason,type)VALUES(' Sep 5 ','Labor Day','FEDERAL');
--INSERT INTO holidays (holiday,reason,type)VALUES(' Nov 11 ','Veterans Day','FEDERAL');
--
