--CREATE TABLE IF NOT EXISTS `contact_msg` (
--  `contact_id` int AUTO_INCREMENT,
--  `name` varchar(100) NOT NULL,
--  `mobile_num` varchar(10) NOT NULL,
--  `email` varchar(100) NOT NULL,
--  `subject` varchar(100) NOT NULL,
--  `message` varchar(500) NOT NULL,
--  `status` varchar(10) NOT NULL,
--  `created_at` TIMESTAMP NOT NULL,
--  `created_by` varchar(50) NOT NULL,
--  `updated_at` TIMESTAMP DEFAULT NULL,
--  `updated_by` varchar(50) DEFAULT NULL,
--  PRIMARY KEY(`contact_id`)
--);
--
--CREATE TABLE IF NOT EXISTS `holidays`(
--`holiday` varchar(100) NOT NULL,
--`reason` varchar(100) NOT NULL,
--`type` ENUM('FEDERAL', 'FESTIVAL') NOT NULL
----`type` varchar(100) NOT NULL
--);